services:
  mysql:
    image: mysql:latest
    container_name: mysql-aventia-oppgave
    environment:
      MYSQL_ROOT_PASSWORD: "mysqldbpassword"
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"